version: '3.7'

services:

  php:
    build:
      context: ./docker/laravel/php
      dockerfile: Dockerfile-php8
    container_name: ${DOCKER_APP}-php
    volumes:
      - "./app:/var/www/html"
    expose:
      - 9000
    ports:
      - "9000:9000"
    links:
      - mysql
      - redis
    networks:
      - develop-network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  phpqueue:
    build:
      context: ./docker/laravel/php
      dockerfile: Dockerfile-php8-queue
    container_name: ${DOCKER_APP}-php-queue
    volumes:
      - "./app:/var/www/html"
    expose:
      - 9000
    links:
      - mysql
      - redis
    networks:
      - develop-network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable-alpine
    container_name: ${DOCKER_APP}-nginx
    expose:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - develop-network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  mysql:
    build:
      context: ./docker/mysql
      network: host
    container_name: ${DOCKER_APP}-mysql
    restart: unless-stopped
    tty: true
    expose:
      - "3306"
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASS}
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/wt-my.cnf
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - develop-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_APP}-phpmyadmin
    restart: always
    expose:
      - "80"
    ports:
      - "8001:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - develop-network

  redis:
    image: redis:5.0-alpine
    container_name: ${DOCKER_APP}-redis
    networks:
      - develop-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${DOCKER_APP}-rabbitmq
    expose:
      - "5672"
      - "15672"
      - "25672"
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq/enable_plugins:/etc/rabbitmq/enable_plugins
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge
