version: '3.7'

services:

  php:
    build:
      context: ./docker/laravel/php
      dockerfile: Dockerfile-php8
    container_name: ${DOCKER_APP}-php
    volumes:
      - "./app:/var/www/html"
    expose:
      - 9000
    ports:
      - "9000:9000"
    # environment:
    #   XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - mysql
      - redis
    networks:
      - develop-network

  nginx:
    image: nginx:stable-alpine
    container_name: ${DOCKER_APP}-nginx
    expose:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - develop-network

  mysql:
    build:
      context: ./docker/mysql
      network: host
    container_name: ${DOCKER_APP}-mysql
    restart: unless-stopped
    tty: true
    expose:
      - "3306"
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASS}
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/wt-my.cnf
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - develop-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_APP}-phpmyadmin
    restart: always
    expose:
      - "80"
    ports:
      - "8001:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      #PMA_ARBITRARY: 1
    networks:
      - develop-network

  redis:
    image: redis:5.0-alpine
    container_name: ${DOCKER_APP}-redis
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge
